name: cla-checking
on: 
  workflow_dispatch:
  pull_request:

jobs:
  comment-on-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: install npm packages
        run: npm install
      - name: run index.js
        run: node .github/actions/index.js
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}